INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (1, '\n\n	\n	\n		\n					Flowers		\n	\n', '\n	\n	Miley Cyrus\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (2, '\n\n	\n	\n		\n					Calm Down		\n	\n', '\n	\n	Rema & Selena Gomez\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (3, '\n\n	\n	\n		\n					Kill Bill		\n	\n', '\n	\n	SZA\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (4, '\n\n	\n	\n		\n					Anti-Hero		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (5, '\n\n	\n	\n		\n					Die For You		\n	\n', '\n	\n	The Weeknd & Ariana Grande\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (6, '\n\n	\n	\n		\n					As It Was		\n	\n', '\n	\n	Harry Styles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (7, '\n\n	\n	\n		\n					Unholy		\n	\n', '\n	\n	Sam Smith & Kim Petras\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (8, '\n\n	\n	\n		\n					I\'m Good (Blue)		\n	\n', '\n	\n	David Guetta & Bebe Rexha\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (9, '\n\n	\n	\n		\n					Creepin\'		\n	\n', '\n	\n	Metro Boomin, The Weeknd & 21 Savage\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (10, '\n\n	\n	\n		\n					Last Night		\n	\n', '\n	\n	Morgan Wallen\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (11, '\n\n	\n	\n		\n					La Bebe		\n	\n', '\n	\n	Yng Lvcas x Peso Pluma\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (12, '\n\n	\n	\n		\n					Ella Baila Sola		\n	\n', '\n	\n	Eslabon Armado X Peso Pluma\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (13, '\n\n	\n	\n		\n					Until I Found You		\n	\n', '\n	\n	Stephen Sanchez\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (14, '\n\n	\n	\n		\n					I Ain\'t Worried		\n	\n', '\n	\n	OneRepublic\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (15, '\n\n	\n	\n		\n					Save Your Tears		\n	\n', '\n	\n	The Weeknd & Ariana Grande\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (16, '\n\n	\n	\n		\n					Another Love		\n	\n', '\n	\n	Tom Odell\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (17, '\n\n	\n	\n		\n					Seven		\n	\n', '\n	\n	Jung Kook Featuring Latto\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (18, '\n\n	\n	\n		\n					TQG		\n	\n', '\n	\n	Karol G x Shakira\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (19, '\n\n	\n	\n		\n					La Bachata		\n	\n', '\n	\n	Manuel Turizo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (20, '\n\n	\n	\n		\n					Cupid		\n	\n', '\n	\n	Fifty Fifty\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (21, '\n\n	\n	\n		\n					Golden Hour		\n	\n', '\n	\n	JVKE\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (22, '\n\n	\n	\n		\n					Bzrp Music Sessions, Vol. 53		\n	\n', '\n	\n	Bizarrap & Shakira\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (23, '\n\n	\n	\n		\n					Escapism		\n	\n', '\n	\n	RAYE Featuring 070 Shake\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (24, '\n\n	\n	\n		\n					Under The Influence		\n	\n', '\n	\n	Chris Brown\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (25, '\n\n	\n	\n		\n					Un x100to		\n	\n', '\n	\n	Grupo Frontera X Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (26, '\n\n	\n	\n		\n					Boy\'s A Liar, Pt. 2		\n	\n', '\n	\n	PinkPantheress & Ice Spice\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (27, '\n\n	\n	\n		\n					Cruel Summer		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (28, '\n\n	\n	\n		\n					Something In The Orange		\n	\n', '\n	\n	Zach Bryan\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (29, '\n\n	\n	\n		\n					Blinding Lights		\n	\n', '\n	\n	The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (30, '\n\n	\n	\n		\n					Heat Waves		\n	\n', '\n	\n	Glass Animals\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (31, '\n\n	\n	\n		\n					Snooze		\n	\n', '\n	\n	SZA\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (32, '\n\n	\n	\n		\n					Me Porto Bonito		\n	\n', '\n	\n	Bad Bunny & Chencho Corleone\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (33, '\n\n	\n	\n		\n					Sure Thing		\n	\n', '\n	\n	Miguel\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (34, '\n\n	\n	\n		\n					Rich Flex		\n	\n', '\n	\n	Drake & 21 Savage\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (35, '\n\n	\n	\n		\n					Levitating		\n	\n', '\n	\n	Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (36, '\n\n	\n	\n		\n					Starboy		\n	\n', '\n	\n	The Weeknd Featuring Daft Punk\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (37, '\n\n	\n	\n		\n					Stay		\n	\n', '\n	\n	The Kid LAROI & Justin Bieber\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (38, '\n\n	\n	\n		\n					Perfect		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (39, '\n\n	\n	\n		\n					Cold Heart (PNAU Remix)		\n	\n', '\n	\n	Elton John & Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (40, '\n\n	\n	\n		\n					Bzrp Music Sessions, Vol. 52		\n	\n', '\n	\n	Bizarrap & Quevedo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (41, '\n\n	\n	\n		\n					OMG		\n	\n', '\n	\n	NewJeans\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (42, '\n\n	\n	\n		\n					Idol		\n	\n', '\n	\n	YOASOBI\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (43, '\n\n	\n	\n		\n					Shivers		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (44, '\n\n	\n	\n		\n					Cuff It		\n	\n', '\n	\n	Beyonce\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (45, '\n\n	\n	\n		\n					Sweater Weather		\n	\n', '\n	\n	The Neighbourhood\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (46, '\n\n	\n	\n		\n					Daylight		\n	\n', '\n	\n	David Kushner\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (47, '\n\n	\n	\n		\n					Sunflower (Spider-Man: Into The Spider-Verse)		\n	\n', '\n	\n	Post Malone & Swae Lee\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (48, '\n\n	\n	\n		\n					Mockingbird		\n	\n', '\n	\n	Eminem\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (49, '\n\n	\n	\n		\n					Someone You Loved		\n	\n', '\n	\n	Lewis Capaldi\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (50, '\n\n	\n	\n		\n					Titi Me Pregunto		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (51, '\n\n	\n	\n		\n					People		\n	\n', '\n	\n	Libianca\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (52, '\n\n	\n	\n		\n					Ditto		\n	\n', '\n	\n	NewJeans\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (53, '\n\n	\n	\n		\n					Yandel 150		\n	\n', '\n	\n	Yandel & Feid\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (54, '\n\n	\n	\n		\n					Hey Mor		\n	\n', '\n	\n	Ozuna Featuring Feid\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (55, '\n\n	\n	\n		\n					Bones		\n	\n', '\n	\n	Imagine Dragons\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (56, '\n\n	\n	\n		\n					I Wanna Be Yours		\n	\n', '\n	\n	Arctic Monkeys\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (57, '\n\n	\n	\n		\n					Made You Look		\n	\n', '\n	\n	Meghan Trainor\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (58, '\n\n	\n	\n		\n					Fast Car		\n	\n', '\n	\n	Luke Combs\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (59, '\n\n	\n	\n		\n					Bad Habits		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (60, '\n\n	\n	\n		\n					Believer		\n	\n', '\n	\n	Imagine Dragons\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (61, '\n\n	\n	\n		\n					Like Crazy		\n	\n', '\n	\n	Jimin\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (62, '\n\n	\n	\n		\n					Ojitos Lindos		\n	\n', '\n	\n	Bad Bunny & Bomba Estereo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (63, '\n\n	\n	\n		\n					Dance The Night		\n	\n', '\n	\n	Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (64, '\n\n	\n	\n		\n					Viva La Vida		\n	\n', '\n	\n	Coldplay\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (65, '\n\n	\n	\n		\n					Shape Of You		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (66, '\n\n	\n	\n		\n					Vampire		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (67, '\n\n	\n	\n		\n					Blank Space		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (68, '\n\n	\n	\n		\n					Classy 101		\n	\n', '\n	\n	Feid x Young Miko\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (69, '\n\n	\n	\n		\n					Unstoppable		\n	\n', '\n	\n	Sia\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (70, '\n\n	\n	\n		\n					Yellow		\n	\n', '\n	\n	Coldplay\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (71, '\n\n	\n	\n		\n					You Proof		\n	\n', '\n	\n	Morgan Wallen\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (72, '\n\n	\n	\n		\n					Lavender Haze		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (73, '\n\n	\n	\n		\n					Snap		\n	\n', '\n	\n	Rosa Linn\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (74, '\n\n	\n	\n		\n					Where She Goes		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (75, '\n\n	\n	\n		\n					Jimmy Cooks		\n	\n', '\n	\n	Drake Featuring 21 Savage\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (76, '\n\n	\n	\n		\n					LaLa		\n	\n', '\n	\n	Myke Towers\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (77, '\n\n	\n	\n		\n					Summertime Sadness		\n	\n', '\n	\n	Lana Del Rey vs. Cedric Gervais\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (78, '\n\n	\n	\n		\n					Que Vuelvas		\n	\n', '\n	\n	Carin Leon X Grupo Frontera\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (79, '\n\n	\n	\n		\n					Just Wanna Rock		\n	\n', '\n	\n	Lil Uzi Vert\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (80, '\n\n	\n	\n		\n					Superhero (Heroes & Villains)		\n	\n', '\n	\n	Metro Boomin, Future & Chris Brown\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (81, '\n\n	\n	\n		\n					Bad Habit		\n	\n', '\n	\n	Steve Lacy\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (82, '\n\n	\n	\n		\n					Paint The Town Red		\n	\n', '\n	\n	Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (83, '\n\n	\n	\n		\n					Without Me		\n	\n', '\n	\n	Eminem\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (84, '\n\n	\n	\n		\n					Fukumean		\n	\n', '\n	\n	Gunna\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (85, '\n\n	\n	\n		\n					Lovely		\n	\n', '\n	\n	Billie Eilish & Khalid\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (86, '\n\n	\n	\n		\n					La Jumpa		\n	\n', '\n	\n	Arcangel & Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (87, '\n\n	\n	\n		\n					Shut Up My Moms Calling		\n	\n', '\n	\n	Hotel Ugly\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (88, '\n\n	\n	\n		\n					Karma		\n	\n', '\n	\n	Taylor Swift Featuring Ice Spice\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (89, '\n\n	\n	\n		\n					Baby Shark		\n	\n', '\n	\n	Pinkfong\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (90, '\n\n	\n	\n		\n					Por Las Noches		\n	\n', '\n	\n	Peso Pluma\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (91, '\n\n	\n	\n		\n					No Role Modelz		\n	\n', '\n	\n	J. Cole\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (92, '\n\n	\n	\n		\n					Beso		\n	\n', '\n	\n	Rosalia & Rauw Alejandro\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (93, '\n\n	\n	\n		\n					PRC		\n	\n', '\n	\n	Peso Pluma X Natanael Cano\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (94, '\n\n	\n	\n		\n					Everybody Wants To Rule The World		\n	\n', '\n	\n	Tears For Fears\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (95, '\n\n	\n	\n		\n					All I Want For Christmas Is You		\n	\n', '\n	\n	Mariah Carey\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (96, '\n\n	\n	\n		\n					Counting Stars		\n	\n', '\n	\n	OneRepublic\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (97, '\n\n	\n	\n		\n					Miss You		\n	\n', '\n	\n	Oliver Tree & Robin Schulz\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (98, '\n\n	\n	\n		\n					Sprinter		\n	\n', '\n	\n	Dave & Central Cee\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (99, '\n\n	\n	\n		\n					El Azul		\n	\n', '\n	\n	Junior H x Peso Pluma\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (100, '\n\n	\n	\n		\n					Here With Me		\n	\n', '\n	\n	d4vd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (101, '\n\n	\n	\n		\n					Riptide		\n	\n', '\n	\n	Vance Joy\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (102, '\n\n	\n	\n		\n					Bebe Dame		\n	\n', '\n	\n	Fuerza Regida X Grupo Frontera\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (103, '\n\n	\n	\n		\n					AMG		\n	\n', '\n	\n	Gabito Ballesteros, Peso Pluma & Natanael Cano\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (104, '\n\n	\n	\n		\n					Take Me To Church		\n	\n', '\n	\n	Hozier\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (105, '\n\n	\n	\n		\n					Circles		\n	\n', '\n	\n	Post Malone\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (106, '\n\n	\n	\n		\n					Thinkin\' Bout Me		\n	\n', '\n	\n	Morgan Wallen\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (107, '\n\n	\n	\n		\n					Easy On Me		\n	\n', '\n	\n	Adele\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (108, '\n\n	\n	\n		\n					Players		\n	\n', '\n	\n	Coi Leray\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (109, '\n\n	\n	\n		\n					Take On Me		\n	\n', '\n	\n	a-ha\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (110, '\n\n	\n	\n		\n					All My Life		\n	\n', '\n	\n	Lil Durk Featuring J. Cole\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (111, '\n\n	\n	\n		\n					What Was I Made For?		\n	\n', '\n	\n	Billie Eilish\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (112, '\n\n	\n	\n		\n					Despecha		\n	\n', '\n	\n	Rosalia\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (113, '\n\n	\n	\n		\n					Watermelon Sugar		\n	\n', '\n	\n	Harry Styles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (114, '\n\n	\n	\n		\n					Feliz Cumpleanos Ferxxo		\n	\n', '\n	\n	Feid\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (115, '\n\n	\n	\n		\n					Chemical		\n	\n', '\n	\n	Post Malone\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (116, '\n\n	\n	\n		\n					Sunroof		\n	\n', '\n	\n	Nicky Youre & dazy\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (117, '\n\n	\n	\n		\n					Super Shy		\n	\n', '\n	\n	NewJeans\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (118, '\n\n	\n	\n		\n					Gangsta\'s Paradise		\n	\n', '\n	\n	Coolio Featuring L.V.\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (119, '\n\n	\n	\n		\n					Sweet Child O\' Mine		\n	\n', '\n	\n	Guns N\' Roses\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (120, '\n\n	\n	\n		\n					Style		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (121, '\n\n	\n	\n		\n					Provenza		\n	\n', '\n	\n	Karol G\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (122, '\n\n	\n	\n		\n					When I Was Your Man		\n	\n', '\n	\n	Bruno Mars\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (123, '\n\n	\n	\n		\n					Barbie World		\n	\n', '\n	\n	Nicki Minaj & Ice Spice With Aqua\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (124, '\n\n	\n	\n		\n					Wasted On You		\n	\n', '\n	\n	Morgan Wallen\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (125, '\n\n	\n	\n		\n					Baby Don\'t Hurt Me		\n	\n', '\n	\n	David Guetta, Anne-Marie & Coi Leray\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (126, '\n\n	\n	\n		\n					Shallow		\n	\n', '\n	\n	Lady Gaga & Bradley Cooper\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (127, '\n\n	\n	\n		\n					Favorite Song		\n	\n', '\n	\n	Toosii\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (128, '\n\n	\n	\n		\n					Lift Me Up		\n	\n', '\n	\n	Rihanna\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (129, '\n\n	\n	\n		\n					Last Christmas		\n	\n', '\n	\n	Wham!\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (130, '\n\n	\n	\n		\n					Set Fire To The Rain		\n	\n', '\n	\n	Adele\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (131, '\n\n	\n	\n		\n					Moonlight		\n	\n', '\n	\n	Kali Uchis\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (132, '\n\n	\n	\n		\n					Eyes Closed		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (133, '\n\n	\n	\n		\n					See You Again		\n	\n', '\n	\n	Tyler, The Creator Featuring Kali Uchis\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (134, '\n\n	\n	\n		\n					Efecto		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (135, '\n\n	\n	\n		\n					Miracle		\n	\n', '\n	\n	Calvin Harris & Ellie Goulding\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (136, '\n\n	\n	\n		\n					Dandelions		\n	\n', '\n	\n	Ruth B.\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (137, '\n\n	\n	\n		\n					Lady Gaga		\n	\n', '\n	\n	Peso Pluma, Gabito Ballesteros & Junior H\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (138, '\n\n	\n	\n		\n					Can\'t Hold Us		\n	\n', '\n	\n	Macklemore & Ryan Lewis Featuring Ray Dalton\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (139, '\n\n	\n	\n		\n					Too Many Nights		\n	\n', '\n	\n	Metro Boomin Featuring Don Toliver & Future\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (140, '\n\n	\n	\n		\n					10:35		\n	\n', '\n	\n	Tiesto Featuring Tate McRae\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (141, '\n\n	\n	\n		\n					No Se Va		\n	\n', '\n	\n	Grupo Frontera\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (142, '\n\n	\n	\n		\n					TQM		\n	\n', '\n	\n	Fuerza Regida\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (143, '\n\n	\n	\n		\n					Shake It Off		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (144, '\n\n	\n	\n		\n					Wait For U		\n	\n', '\n	\n	Future Featuring Drake & Tems\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (145, '\n\n	\n	\n		\n					Cardigan		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (146, '\n\n	\n	\n		\n					Rockin\' Around The Christmas Tree		\n	\n', '\n	\n	Brenda Lee\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (147, '\n\n	\n	\n		\n					Hype Boy		\n	\n', '\n	\n	NewJeans\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (148, '\n\n	\n	\n		\n					Search & Rescue		\n	\n', '\n	\n	Drake\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (149, '\n\n	\n	\n		\n					Kick Back		\n	\n', '\n	\n	Kenshi Yonezu\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (150, '\n\n	\n	\n		\n					Fragil		\n	\n', '\n	\n	Yahritza y Su Esencia x Grupo Frontera\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (151, '\n\n	\n	\n		\n					Bzrp Music Sessions, Vol. 55		\n	\n', '\n	\n	Bizarrap & Peso Pluma\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (152, '\n\n	\n	\n		\n					I Am		\n	\n', '\n	\n	IVE\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (153, '\n\n	\n	\n		\n					Lover		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (154, '\n\n	\n	\n		\n					Rock And A Hard Place		\n	\n', '\n	\n	Bailey Zimmerman\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (155, '\n\n	\n	\n		\n					Every Breath You Take		\n	\n', '\n	\n	The Police\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (156, '\n\n	\n	\n		\n					Popular		\n	\n', '\n	\n	The Weeknd, Playboi Carti & Madonna\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (157, '\n\n	\n	\n		\n					Dreams		\n	\n', '\n	\n	Fleetwood Mac\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (158, '\n\n	\n	\n		\n					Something Just Like This		\n	\n', '\n	\n	The Chainsmokers & Coldplay\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (159, '\n\n	\n	\n		\n					Columbia		\n	\n', '\n	\n	Quevedo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (160, '\n\n	\n	\n		\n					Flower		\n	\n', '\n	\n	Jisoo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (161, '\n\n	\n	\n		\n					Don\'t Blame Me		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (162, '\n\n	\n	\n		\n					Fin de Semana		\n	\n', '\n	\n	Junior H X Oscar Maydon\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (163, '\n\n	\n	\n		\n					Romantic Homicide		\n	\n', '\n	\n	d4vd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (164, '\n\n	\n	\n		\n					Enemy		\n	\n', '\n	\n	Imagine Dragons X JID\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (165, '\n\n	\n	\n		\n					Jingle Bell Rock		\n	\n', '\n	\n	Bobby Helms\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (166, '\n\n	\n	\n		\n					Money Trees		\n	\n', '\n	\n	Kendrick Lamar Featuring Jay Rock\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (167, '\n\n	\n	\n		\n					Bloody Mary		\n	\n', '\n	\n	Lady Gaga\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (168, '\n\n	\n	\n		\n					Moscow Mule		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (169, '\n\n	\n	\n		\n					Smells Like Teen Spirit		\n	\n', '\n	\n	Nirvana\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (170, '\n\n	\n	\n		\n					El Merengue		\n	\n', '\n	\n	Marshmello & Manuel Turizo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (171, '\n\n	\n	\n		\n					Queencard		\n	\n', '\n	\n	(G)I-DLE\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (172, '\n\n	\n	\n		\n					Amargura		\n	\n', '\n	\n	Karol G\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (173, '\n\n	\n	\n		\n					Thunder		\n	\n', '\n	\n	Imagine Dragons\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (174, '\n\n	\n	\n		\n					El Gordo Trae El Mando		\n	\n', '\n	\n	Chino Pacas\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (175, '\n\n	\n	\n		\n					Qlona		\n	\n', '\n	\n	Karol G & Peso Pluma\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (176, '\n\n	\n	\n		\n					Creep		\n	\n', '\n	\n	Radiohead\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (177, '\n\n	\n	\n		\n					Sabor Fresa		\n	\n', '\n	\n	Fuerza Regida\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (178, '\n\n	\n	\n		\n					Tattoo		\n	\n', '\n	\n	Loreen\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (179, '\n\n	\n	\n		\n					Ch y La Pizza		\n	\n', '\n	\n	Fuerza Regida X Natanael Cano\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (180, '\n\n	\n	\n		\n					Nonsense		\n	\n', '\n	\n	Sabrina Carpenter\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (181, '\n\n	\n	\n		\n					Shirt		\n	\n', '\n	\n	SZA\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (182, '\n\n	\n	\n		\n					Antifragile		\n	\n', '\n	\n	LE SSERAFIM\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (183, '\n\n	\n	\n		\n					Trance		\n	\n', '\n	\n	Metro Boomin, Travis Scott & Young Thug\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (184, '\n\n	\n	\n		\n					Coco Chanel		\n	\n', '\n	\n	Eladio Carrion & Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (185, '\n\n	\n	\n		\n					(It Goes Like) Nanana		\n	\n', '\n	\n	Peggy Gou\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (186, '\n\n	\n	\n		\n					Tulum		\n	\n', '\n	\n	Peso Pluma & Grupo Frontera\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (187, '\n\n	\n	\n		\n					Late Night Talking		\n	\n', '\n	\n	Harry Styles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (188, '\n\n	\n	\n		\n					Shut Down		\n	\n', '\n	\n	BLACKPINK\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (189, '\n\n	\n	\n		\n					Primera Cita		\n	\n', '\n	\n	Carin Leon\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (190, '\n\n	\n	\n		\n					Happier Than Ever		\n	\n', '\n	\n	Billie Eilish\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (191, '\n\n	\n	\n		\n					Chorrito Pa Las Animas		\n	\n', '\n	\n	Feid\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (192, '\n\n	\n	\n		\n					Glimpse Of Us		\n	\n', '\n	\n	Joji\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (193, '\n\n	\n	\n		\n					What It Is (Block Boy)		\n	\n', '\n	\n	Doechii Featuring Kodak Black\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (194, '\n\n	\n	\n		\n					Santa Tell Me		\n	\n', '\n	\n	Ariana Grande\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (195, '\n\n	\n	\n		\n					Subtitle		\n	\n', '\n	\n	Official HIGE DANdism\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (196, '\n\n	\n	\n		\n					About Damn Time		\n	\n', '\n	\n	Lizzo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (197, '\n\n	\n	\n		\n					ETA		\n	\n', '\n	\n	NewJeans\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (198, '\n\n	\n	\n		\n					Ta OK		\n	\n', '\n	\n	DENNIS E MC Kevin O Chris, Maluma & Karol G\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (199, '\n\n	\n	\n		\n					Monotonia		\n	\n', '\n	\n	Shakira + Ozuna\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (200, '\n\n	\n	\n		\n					X Si Volvemos		\n	\n', '\n	\n	Karol G x Romeo Santos\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (201, '\n\n	\n	\n		\n					As It Was		\n	\n', '\n	\n	Harry Styles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (202, '\n\n	\n	\n		\n					Heat Waves		\n	\n', '\n	\n	Glass Animals\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (203, '\n\n	\n	\n		\n					Stay		\n	\n', '\n	\n	The Kid LAROI & Justin Bieber\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (204, '\n\n	\n	\n		\n					Cold Heart (PNAU Remix)		\n	\n', '\n	\n	Elton John & Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (205, '\n\n	\n	\n		\n					Shivers		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (206, '\n\n	\n	\n		\n					Easy On Me		\n	\n', '\n	\n	Adele\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (207, '\n\n	\n	\n		\n					abcdefu		\n	\n', '\n	\n	GAYLE\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (208, '\n\n	\n	\n		\n					Bad Habits		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (209, '\n\n	\n	\n		\n					Enemy		\n	\n', '\n	\n	Imagine Dragons X JID\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (210, '\n\n	\n	\n		\n					Save Your Tears		\n	\n', '\n	\n	The Weeknd & Ariana Grande\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (211, '\n\n	\n	\n		\n					Me Porto Bonito		\n	\n', '\n	\n	Bad Bunny & Chencho Corleone\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (212, '\n\n	\n	\n		\n					Industry Baby		\n	\n', '\n	\n	Lil Nas X & Jack Harlow\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (213, '\n\n	\n	\n		\n					Titi Me Pregunto		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (214, '\n\n	\n	\n		\n					Levitating		\n	\n', '\n	\n	Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (215, '\n\n	\n	\n		\n					Pepas		\n	\n', '\n	\n	Farruko\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (216, '\n\n	\n	\n		\n					Blinding Lights		\n	\n', '\n	\n	The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (217, '\n\n	\n	\n		\n					Love Nwantiti (Ah Ah Ah)		\n	\n', '\n	\n	CKay\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (218, '\n\n	\n	\n		\n					Running Up That Hill (A Deal With God)		\n	\n', '\n	\n	Kate Bush\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (219, '\n\n	\n	\n		\n					Ghost		\n	\n', '\n	\n	Justin Bieber\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (220, '\n\n	\n	\n		\n					First Class		\n	\n', '\n	\n	Jack Harlow\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (221, '\n\n	\n	\n		\n					Happier Than Ever		\n	\n', '\n	\n	Billie Eilish\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (222, '\n\n	\n	\n		\n					Woman		\n	\n', '\n	\n	Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (223, '\n\n	\n	\n		\n					Ojitos Lindos		\n	\n', '\n	\n	Bad Bunny & Bomba Estereo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (224, '\n\n	\n	\n		\n					Where Are You Now		\n	\n', '\n	\n	Lost Frequencies & Calum Scott\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (225, '\n\n	\n	\n		\n					My Universe		\n	\n', '\n	\n	Coldplay x BTS\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (226, '\n\n	\n	\n		\n					Moscow Mule		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (227, '\n\n	\n	\n		\n					Good 4 U		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (228, '\n\n	\n	\n		\n					Efecto		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (229, '\n\n	\n	\n		\n					Bam Bam		\n	\n', '\n	\n	Camila Cabello Featuring Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (230, '\n\n	\n	\n		\n					About Damn Time		\n	\n', '\n	\n	Lizzo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (231, '\n\n	\n	\n		\n					Perfect		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (232, '\n\n	\n	\n		\n					Provenza		\n	\n', '\n	\n	Karol G\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (233, '\n\n	\n	\n		\n					Another Love		\n	\n', '\n	\n	Tom Odell\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (234, '\n\n	\n	\n		\n					Sweater Weather		\n	\n', '\n	\n	The Neighbourhood\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (235, '\n\n	\n	\n		\n					Bzrp Music Sessions, Vol. 52		\n	\n', '\n	\n	Bizarrap & Quevedo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (236, '\n\n	\n	\n		\n					MAMIII		\n	\n', '\n	\n	Becky G X Karol G\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (237, '\n\n	\n	\n		\n					The Motto		\n	\n', '\n	\n	Tiesto & Ava Max\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (238, '\n\n	\n	\n		\n					Butter		\n	\n', '\n	\n	BTS\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (239, '\n\n	\n	\n		\n					Kiss Me More		\n	\n', '\n	\n	Doja Cat Featuring SZA\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (240, '\n\n	\n	\n		\n					Dynamite		\n	\n', '\n	\n	BTS\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (241, '\n\n	\n	\n		\n					Desesperados		\n	\n', '\n	\n	Rauw Alejandro & Chencho Corleone\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (242, '\n\n	\n	\n		\n					We Don\'t Talk About Bruno		\n	\n', '\n	\n	Carolina Gaitan, Mauro Castillo, Adassa, Rhenzy Feliz, Diane Guerrero, Stephanie Beatriz & Encanto Cast\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (243, '\n\n	\n	\n		\n					I Ain\'t Worried		\n	\n', '\n	\n	OneRepublic\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (244, '\n\n	\n	\n		\n					Wait For U		\n	\n', '\n	\n	Future Featuring Drake & Tems\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (245, '\n\n	\n	\n		\n					Believer		\n	\n', '\n	\n	Imagine Dragons\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (246, '\n\n	\n	\n		\n					Watermelon Sugar		\n	\n', '\n	\n	Harry Styles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (247, '\n\n	\n	\n		\n					Sunflower (Spider-Man: Into The Spider-Verse)		\n	\n', '\n	\n	Post Malone & Swae Lee\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (248, '\n\n	\n	\n		\n					Shape Of You		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (249, '\n\n	\n	\n		\n					Thats What I Want		\n	\n', '\n	\n	Lil Nas X\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (250, '\n\n	\n	\n		\n					Glimpse Of Us		\n	\n', '\n	\n	Joji\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (251, '\n\n	\n	\n		\n					Do It To It		\n	\n', '\n	\n	Acraze Featuring Cherish\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (252, '\n\n	\n	\n		\n					Baby Shark		\n	\n', '\n	\n	Pinkfong\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (253, '\n\n	\n	\n		\n					Dance Monkey		\n	\n', '\n	\n	Tones And I\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (254, '\n\n	\n	\n		\n					Someone You Loved		\n	\n', '\n	\n	Lewis Capaldi\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (255, '\n\n	\n	\n		\n					Yonaguni		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (256, '\n\n	\n	\n		\n					Middle Of The Night		\n	\n', '\n	\n	Elley Duhe\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (257, '\n\n	\n	\n		\n					All Too Well (Taylor\'s Version)		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (258, '\n\n	\n	\n		\n					Traitor		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (259, '\n\n	\n	\n		\n					Party		\n	\n', '\n	\n	Bad Bunny & Rauw Alejandro\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (260, '\n\n	\n	\n		\n					Drivers License		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (261, '\n\n	\n	\n		\n					Dakiti		\n	\n', '\n	\n	Bad Bunny & Jhay Cortez\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (262, '\n\n	\n	\n		\n					Late Night Talking		\n	\n', '\n	\n	Harry Styles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (263, '\n\n	\n	\n		\n					Without Me		\n	\n', '\n	\n	Eminem\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (264, '\n\n	\n	\n		\n					Need To Know		\n	\n', '\n	\n	Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (265, '\n\n	\n	\n		\n					Peaches		\n	\n', '\n	\n	Justin Bieber Featuring Daniel Caesar & Giveon\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (266, '\n\n	\n	\n		\n					Don\'t Start Now		\n	\n', '\n	\n	Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (267, '\n\n	\n	\n		\n					Shallow		\n	\n', '\n	\n	Lady Gaga & Bradley Cooper\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (268, '\n\n	\n	\n		\n					Envolver		\n	\n', '\n	\n	Anitta\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (269, '\n\n	\n	\n		\n					Dandelions		\n	\n', '\n	\n	Ruth B.\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (270, '\n\n	\n	\n		\n					Beggin\'		\n	\n', '\n	\n	Maneskin\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (271, '\n\n	\n	\n		\n					Tarot		\n	\n', '\n	\n	Bad Bunny & Jhay Cortez\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (272, '\n\n	\n	\n		\n					Circles		\n	\n', '\n	\n	Post Malone\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (273, '\n\n	\n	\n		\n					Lovely		\n	\n', '\n	\n	Billie Eilish & Khalid\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (274, '\n\n	\n	\n		\n					Yellow		\n	\n', '\n	\n	Coldplay\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (275, '\n\n	\n	\n		\n					Bohemian Rhapsody		\n	\n', '\n	\n	Queen\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (276, '\n\n	\n	\n		\n					Bones		\n	\n', '\n	\n	Imagine Dragons\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (277, '\n\n	\n	\n		\n					Super Gremlin		\n	\n', '\n	\n	Kodak Black\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (278, '\n\n	\n	\n		\n					Lo Siento BB:/		\n	\n', '\n	\n	Tainy, Bad Bunny & Julieta Venegas\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (279, '\n\n	\n	\n		\n					Gangsta\'s Paradise		\n	\n', '\n	\n	Coolio Featuring L.V.\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (280, '\n\n	\n	\n		\n					Bad Habit		\n	\n', '\n	\n	Steve Lacy\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (281, '\n\n	\n	\n		\n					Jimmy Cooks		\n	\n', '\n	\n	Drake Featuring 21 Savage\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (282, '\n\n	\n	\n		\n					Te Felicito		\n	\n', '\n	\n	Shakira & Rauw Alejandro\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (283, '\n\n	\n	\n		\n					Love Tonight		\n	\n', '\n	\n	Shouse\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (284, '\n\n	\n	\n		\n					Infinity		\n	\n', '\n	\n	Jaymes Young\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (285, '\n\n	\n	\n		\n					Montero (Call Me By Your Name)		\n	\n', '\n	\n	Lil Nas X\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (286, '\n\n	\n	\n		\n					Smells Like Teen Spirit		\n	\n', '\n	\n	Nirvana\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (287, '\n\n	\n	\n		\n					I Like You (A Happier Song)		\n	\n', '\n	\n	Post Malone Featuring Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (288, '\n\n	\n	\n		\n					All I Want For Christmas Is You		\n	\n', '\n	\n	Mariah Carey\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (289, '\n\n	\n	\n		\n					Counting Stars		\n	\n', '\n	\n	OneRepublic\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (290, '\n\n	\n	\n		\n					La Bachata		\n	\n', '\n	\n	Manuel Turizo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (291, '\n\n	\n	\n		\n					One Right Now		\n	\n', '\n	\n	Post Malone & The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (292, '\n\n	\n	\n		\n					Something Just Like This		\n	\n', '\n	\n	The Chainsmokers & Coldplay\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (293, '\n\n	\n	\n		\n					I\'m Good (Blue)		\n	\n', '\n	\n	David Guetta & Bebe Rexha\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (294, '\n\n	\n	\n		\n					Pink Venom		\n	\n', '\n	\n	BLACKPINK\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (295, '\n\n	\n	\n		\n					Under The Influence		\n	\n', '\n	\n	Chris Brown\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (296, '\n\n	\n	\n		\n					Neverita		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (297, '\n\n	\n	\n		\n					No Role Modelz		\n	\n', '\n	\n	J. Cole\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (298, '\n\n	\n	\n		\n					Unholy		\n	\n', '\n	\n	Sam Smith & Kim Petras\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (299, '\n\n	\n	\n		\n					Break My Soul		\n	\n', '\n	\n	Beyonce\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (300, '\n\n	\n	\n		\n					Starboy		\n	\n', '\n	\n	The Weeknd Featuring Daft Punk\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (301, '\n\n	\n	\n		\n					Dreams		\n	\n', '\n	\n	Fleetwood Mac\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (302, '\n\n	\n	\n		\n					Peru		\n	\n', '\n	\n	Fireboy DML & Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (303, '\n\n	\n	\n		\n					Die For You		\n	\n', '\n	\n	The Weeknd & Ariana Grande\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (304, '\n\n	\n	\n		\n					Despecha		\n	\n', '\n	\n	Rosalia\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (305, '\n\n	\n	\n		\n					Bad Guy		\n	\n', '\n	\n	Billie Eilish\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (306, '\n\n	\n	\n		\n					Left And Right		\n	\n', '\n	\n	Charlie Puth Featuring Jung Kook\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (307, '\n\n	\n	\n		\n					Despues de La Playa		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (308, '\n\n	\n	\n		\n					Sunroof		\n	\n', '\n	\n	Nicky Youre & dazy\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (309, '\n\n	\n	\n		\n					Leave The Door Open		\n	\n', '\n	\n	Silk Sonic (Bruno Mars & Anderson .Paak)\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (310, '\n\n	\n	\n		\n					Oh My God		\n	\n', '\n	\n	Adele\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (311, '\n\n	\n	\n		\n					Light Switch		\n	\n', '\n	\n	Charlie Puth\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (312, '\n\n	\n	\n		\n					Deja Vu		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (313, '\n\n	\n	\n		\n					Take Me To Church		\n	\n', '\n	\n	Hozier\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (314, '\n\n	\n	\n		\n					Sweet Child O\' Mine		\n	\n', '\n	\n	Guns N\' Roses\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (315, '\n\n	\n	\n		\n					Unstoppable		\n	\n', '\n	\n	Sia\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (316, '\n\n	\n	\n		\n					Riptide		\n	\n', '\n	\n	Vance Joy\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (317, '\n\n	\n	\n		\n					The Real Slim Shady		\n	\n', '\n	\n	Eminem\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (318, '\n\n	\n	\n		\n					Mr. Brightside		\n	\n', '\n	\n	The Killers\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (319, '\n\n	\n	\n		\n					Big Energy		\n	\n', '\n	\n	Latto\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (320, '\n\n	\n	\n		\n					Lose Yourself		\n	\n', '\n	\n	Eminem\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (321, '\n\n	\n	\n		\n					La Corriente		\n	\n', '\n	\n	Bad Bunny & Tony Dize\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (322, '\n\n	\n	\n		\n					Until I Found You		\n	\n', '\n	\n	Stephen Sanchez\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (323, '\n\n	\n	\n		\n					Una Noche En Medellin		\n	\n', '\n	\n	Cris Mj\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (324, '\n\n	\n	\n		\n					Calm Down		\n	\n', '\n	\n	Rema & Selena Gomez\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (325, '\n\n	\n	\n		\n					Surface Pressure		\n	\n', '\n	\n	Jessica Darrow\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (326, '\n\n	\n	\n		\n					Super Freaky Girl		\n	\n', '\n	\n	Nicki Minaj\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (327, '\n\n	\n	\n		\n					Astronaut In The Ocean		\n	\n', '\n	\n	Masked Wolf\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (328, '\n\n	\n	\n		\n					Vegas		\n	\n', '\n	\n	Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (329, '\n\n	\n	\n		\n					Ultra Solo		\n	\n', '\n	\n	Polima WestCoast Featuring Pailita\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (330, '\n\n	\n	\n		\n					Something In The Orange		\n	\n', '\n	\n	Zach Bryan\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (331, '\n\n	\n	\n		\n					In Da Club		\n	\n', '\n	\n	50 Cent\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (332, '\n\n	\n	\n		\n					Hotel California		\n	\n', '\n	\n	Eagles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (333, '\n\n	\n	\n		\n					Snap		\n	\n', '\n	\n	Rosa Linn\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (334, '\n\n	\n	\n		\n					505		\n	\n', '\n	\n	Arctic Monkeys\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (335, '\n\n	\n	\n		\n					You Proof		\n	\n', '\n	\n	Morgan Wallen\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (336, '\n\n	\n	\n		\n					Knife Talk		\n	\n', '\n	\n	Drake Featuring 21 Savage & Project Pat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (337, '\n\n	\n	\n		\n					Un Ratito		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (338, '\n\n	\n	\n		\n					Last Christmas		\n	\n', '\n	\n	Wham!\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (339, '\n\n	\n	\n		\n					Take On Me		\n	\n', '\n	\n	a-ha\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (340, '\n\n	\n	\n		\n					You Right		\n	\n', '\n	\n	Doja Cat & The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (341, '\n\n	\n	\n		\n					Meet Me At Our Spot		\n	\n', '\n	\n	THE ANXIETY: WILLOW & Tyler Cole\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (342, '\n\n	\n	\n		\n					Moth To A Flame		\n	\n', '\n	\n	Swedish House Mafia & The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (343, '\n\n	\n	\n		\n					Don\'t Stop Believin\'		\n	\n', '\n	\n	Journey\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (344, '\n\n	\n	\n		\n					She\'s All I Wanna Be		\n	\n', '\n	\n	Tate McRae\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (345, '\n\n	\n	\n		\n					Boyfriend		\n	\n', '\n	\n	Dove Cameron\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (346, '\n\n	\n	\n		\n					Pushin P		\n	\n', '\n	\n	Gunna & Future Featuring Young Thug\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (347, '\n\n	\n	\n		\n					I Love You So		\n	\n', '\n	\n	The Walters\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (348, '\n\n	\n	\n		\n					Thunderstruck		\n	\n', '\n	\n	AC/DC\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (349, '\n\n	\n	\n		\n					Mood		\n	\n', '\n	\n	24kGoldn Featuring iann dior\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (350, '\n\n	\n	\n		\n					Smokin Out The Window		\n	\n', '\n	\n	Silk Sonic (Bruno Mars & Anderson .Paak)\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (351, '\n\n	\n	\n		\n					2step		\n	\n', '\n	\n	Ed Sheeran Featuring Lil Baby\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (352, '\n\n	\n	\n		\n					One Kiss		\n	\n', '\n	\n	Calvin Harris & Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (353, '\n\n	\n	\n		\n					Despacito		\n	\n', '\n	\n	Luis Fonsi & Daddy Yankee Featuring Justin Bieber\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (354, '\n\n	\n	\n		\n					Closer		\n	\n', '\n	\n	The Chainsmokers Featuring Halsey\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (355, '\n\n	\n	\n		\n					Rockin\' Around The Christmas Tree		\n	\n', '\n	\n	Brenda Lee\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (356, '\n\n	\n	\n		\n					Last Last		\n	\n', '\n	\n	Burna Boy\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (357, '\n\n	\n	\n		\n					Money		\n	\n', '\n	\n	LISA\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (358, '\n\n	\n	\n		\n					Ferrari		\n	\n', '\n	\n	James Hype & Miggy Dela Rosa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (359, '\n\n	\n	\n		\n					Todo de Ti		\n	\n', '\n	\n	Rauw Alejandro\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (360, '\n\n	\n	\n		\n					Love Dive		\n	\n', '\n	\n	IVE\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (361, '\n\n	\n	\n		\n					There\'s Nothing Holdin\' Me Back		\n	\n', '\n	\n	Shawn Mendes\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (362, '\n\n	\n	\n		\n					Wasted On You		\n	\n', '\n	\n	Morgan Wallen\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (363, '\n\n	\n	\n		\n					The Kind Of Love We Make		\n	\n', '\n	\n	Luke Combs\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (364, '\n\n	\n	\n		\n					Cuff It		\n	\n', '\n	\n	Beyonce\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (365, '\n\n	\n	\n		\n					Fingers Crossed		\n	\n', '\n	\n	Lauren Spencer Smith\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (366, '\n\n	\n	\n		\n					Toxic		\n	\n', '\n	\n	BoyWithUke\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (367, '\n\n	\n	\n		\n					Jingle Bell Rock		\n	\n', '\n	\n	Bobby Helms\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (368, '\n\n	\n	\n		\n					Only Love Can Hurt Like This		\n	\n', '\n	\n	Paloma Faith\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (369, '\n\n	\n	\n		\n					I Hate U		\n	\n', '\n	\n	SZA\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (370, '\n\n	\n	\n		\n					Every Breath You Take		\n	\n', '\n	\n	The Police\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (371, '\n\n	\n	\n		\n					Un Coco		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (372, '\n\n	\n	\n		\n					Fancy Like		\n	\n', '\n	\n	Walker Hayes\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (373, '\n\n	\n	\n		\n					Andrea		\n	\n', '\n	\n	Bad Bunny & Buscabulla\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (374, '\n\n	\n	\n		\n					La Cancion		\n	\n', '\n	\n	J Balvin & Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (375, '\n\n	\n	\n		\n					Permission To Dance		\n	\n', '\n	\n	BTS\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (376, '\n\n	\n	\n		\n					The Hills		\n	\n', '\n	\n	The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (377, '\n\n	\n	\n		\n					Doja		\n	\n', '\n	\n	Central Cee\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (378, '\n\n	\n	\n		\n					Hold My Hand		\n	\n', '\n	\n	Lady Gaga\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (379, '\n\n	\n	\n		\n					Volvi		\n	\n', '\n	\n	Aventura x Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (380, '\n\n	\n	\n		\n					Shut Down		\n	\n', '\n	\n	BLACKPINK\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (381, '\n\n	\n	\n		\n					Take My Breath		\n	\n', '\n	\n	The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (382, '\n\n	\n	\n		\n					Dos Mil 16		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (383, '\n\n	\n	\n		\n					Tacones Rojos		\n	\n', '\n	\n	Sebastian Yatra\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (384, '\n\n	\n	\n		\n					Better Days		\n	\n', '\n	\n	NEIKED X Mae Muller X Polo G\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (385, '\n\n	\n	\n		\n					Numb		\n	\n', '\n	\n	Marshmello & Khalid\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (386, '\n\n	\n	\n		\n					Sweetest Pie		\n	\n', '\n	\n	Megan Thee Stallion & Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (387, '\n\n	\n	\n		\n					Mon Amour		\n	\n', '\n	\n	zzoilo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (388, '\n\n	\n	\n		\n					Yo No Soy Celoso		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (389, '\n\n	\n	\n		\n					Rock And A Hard Place		\n	\n', '\n	\n	Bailey Zimmerman\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (390, '\n\n	\n	\n		\n					Sacrifice		\n	\n', '\n	\n	The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (391, '\n\n	\n	\n		\n					Medallo		\n	\n', '\n	\n	Blessd, Justin Quiles & Lenny Tavarez\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (392, '\n\n	\n	\n		\n					Dos Oruguitas		\n	\n', '\n	\n	Sebastian Yatra\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (393, '\n\n	\n	\n		\n					Santa Tell Me		\n	\n', '\n	\n	Ariana Grande\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (394, '\n\n	\n	\n		\n					Zankyosanka		\n	\n', '\n	\n	Aimer\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (395, '\n\n	\n	\n		\n					Wait A Minute!		\n	\n', '\n	\n	Willow Smith\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (396, '\n\n	\n	\n		\n					Thunder		\n	\n', '\n	\n	Imagine Dragons\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (397, '\n\n	\n	\n		\n					Billie Jean		\n	\n', '\n	\n	Michael Jackson\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (398, '\n\n	\n	\n		\n					The Family Madrigal		\n	\n', '\n	\n	Stephanie Beatriz, Olga Merediz & Encanto Cast\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (399, '\n\n	\n	\n		\n					It\'s Beginning To Look A Lot Like Christmas		\n	\n', '\n	\n	Michael Buble\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (400, '\n\n	\n	\n		\n					Get Into It (Yuh)		\n	\n', '\n	\n	Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (401, '\n\n	\n	\n		\n					Levitating		\n	\n', '\n	\n	Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (402, '\n\n	\n	\n		\n					Save Your Tears		\n	\n', '\n	\n	The Weeknd & Ariana Grande\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (403, '\n\n	\n	\n		\n					Blinding Lights		\n	\n', '\n	\n	The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (404, '\n\n	\n	\n		\n					Drivers License		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (405, '\n\n	\n	\n		\n					Dynamite		\n	\n', '\n	\n	BTS\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (406, '\n\n	\n	\n		\n					Dakiti		\n	\n', '\n	\n	Bad Bunny & Jhay Cortez\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (407, '\n\n	\n	\n		\n					Montero (Call Me By Your Name)		\n	\n', '\n	\n	Lil Nas X\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (408, '\n\n	\n	\n		\n					Stay		\n	\n', '\n	\n	The Kid LAROI & Justin Bieber\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (409, '\n\n	\n	\n		\n					Good 4 U		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (410, '\n\n	\n	\n		\n					Mood		\n	\n', '\n	\n	24kGoldn Featuring iann dior\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (411, '\n\n	\n	\n		\n					Peaches		\n	\n', '\n	\n	Justin Bieber Featuring Daniel Caesar & Giveon\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (412, '\n\n	\n	\n		\n					Butter		\n	\n', '\n	\n	BTS\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (413, '\n\n	\n	\n		\n					Kiss Me More		\n	\n', '\n	\n	Doja Cat Featuring SZA\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (414, '\n\n	\n	\n		\n					Astronaut In The Ocean		\n	\n', '\n	\n	Masked Wolf\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (415, '\n\n	\n	\n		\n					Bad Habits		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (416, '\n\n	\n	\n		\n					Leave The Door Open		\n	\n', '\n	\n	Silk Sonic (Bruno Mars & Anderson .Paak)\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (417, '\n\n	\n	\n		\n					Heat Waves		\n	\n', '\n	\n	Glass Animals\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (418, '\n\n	\n	\n		\n					Without You		\n	\n', '\n	\n	The Kid LAROI\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (419, '\n\n	\n	\n		\n					Positions		\n	\n', '\n	\n	Ariana Grande\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (420, '\n\n	\n	\n		\n					The Business		\n	\n', '\n	\n	Tiesto\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (421, '\n\n	\n	\n		\n					34+35		\n	\n', '\n	\n	Ariana Grande\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (422, '\n\n	\n	\n		\n					Dance Monkey		\n	\n', '\n	\n	Tones And I\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (423, '\n\n	\n	\n		\n					Watermelon Sugar		\n	\n', '\n	\n	Harry Styles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (424, '\n\n	\n	\n		\n					Hawai		\n	\n', '\n	\n	Maluma\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (425, '\n\n	\n	\n		\n					Beggin\'		\n	\n', '\n	\n	Maneskin\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (426, '\n\n	\n	\n		\n					Industry Baby		\n	\n', '\n	\n	Lil Nas X & Jack Harlow\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (427, '\n\n	\n	\n		\n					Deja Vu		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (428, '\n\n	\n	\n		\n					Someone You Loved		\n	\n', '\n	\n	Lewis Capaldi\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (429, '\n\n	\n	\n		\n					Perfect		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (430, '\n\n	\n	\n		\n					Don\'t Start Now		\n	\n', '\n	\n	Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (431, '\n\n	\n	\n		\n					Lemonade		\n	\n', '\n	\n	Internet Money & Gunna Featuring Don Toliver & NAV\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (432, '\n\n	\n	\n		\n					Goosebumps		\n	\n', '\n	\n	Travis Scott & HVME\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (433, '\n\n	\n	\n		\n					Todo de Ti		\n	\n', '\n	\n	Rauw Alejandro\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (434, '\n\n	\n	\n		\n					You Broke Me First.		\n	\n', '\n	\n	Tate McRae\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (435, '\n\n	\n	\n		\n					Roses		\n	\n', '\n	\n	SAINt JHN\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (436, '\n\n	\n	\n		\n					Streets		\n	\n', '\n	\n	Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (437, '\n\n	\n	\n		\n					Savage Love (Laxed - Siren Beat)		\n	\n', '\n	\n	Jawsh 685 x Jason Derulo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (438, '\n\n	\n	\n		\n					Head & Heart		\n	\n', '\n	\n	Joel Corry X MNEK\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (439, '\n\n	\n	\n		\n					Heartbreak Anniversary		\n	\n', '\n	\n	Giveon\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (440, '\n\n	\n	\n		\n					For The Night		\n	\n', '\n	\n	Pop Smoke Featuring Lil Baby & DaBaby\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (441, '\n\n	\n	\n		\n					Sunflower (Spider-Man: Into The Spider-Verse)		\n	\n', '\n	\n	Post Malone & Swae Lee\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (442, '\n\n	\n	\n		\n					WAP		\n	\n', '\n	\n	Cardi B Featuring Megan Thee Stallion\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (443, '\n\n	\n	\n		\n					Yonaguni		\n	\n', '\n	\n	Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (444, '\n\n	\n	\n		\n					Shape Of You		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (445, '\n\n	\n	\n		\n					La Noche de Anoche		\n	\n', '\n	\n	Bad Bunny & Rosalia\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (446, '\n\n	\n	\n		\n					Rockstar		\n	\n', '\n	\n	DaBaby Featuring Roddy Ricch\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (447, '\n\n	\n	\n		\n					Rapstar		\n	\n', '\n	\n	Polo G\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (448, '\n\n	\n	\n		\n					Baby Shark		\n	\n', '\n	\n	Pinkfong\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (449, '\n\n	\n	\n		\n					Friday		\n	\n', '\n	\n	Riton X Nightcrawlers Featuring Mufasa & Hypeman\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (450, '\n\n	\n	\n		\n					Fiel		\n	\n', '\n	\n	Los Legendarios, Wisin & Jhay Cortez\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (451, '\n\n	\n	\n		\n					What You Know Bout Love		\n	\n', '\n	\n	Pop Smoke\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (452, '\n\n	\n	\n		\n					Whoopty		\n	\n', '\n	\n	CJ\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (453, '\n\n	\n	\n		\n					Believer		\n	\n', '\n	\n	Imagine Dragons\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (454, '\n\n	\n	\n		\n					Up		\n	\n', '\n	\n	Cardi B\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (455, '\n\n	\n	\n		\n					Yoru Ni Kakeru		\n	\n', '\n	\n	YOASOBI\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (456, '\n\n	\n	\n		\n					Therefore I Am		\n	\n', '\n	\n	Billie Eilish\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (457, '\n\n	\n	\n		\n					AM		\n	\n', '\n	\n	Nio Garcia X J Balvin X Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (458, '\n\n	\n	\n		\n					Bad Guy		\n	\n', '\n	\n	Billie Eilish\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (459, '\n\n	\n	\n		\n					Traitor		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (460, '\n\n	\n	\n		\n					Before You Go		\n	\n', '\n	\n	Lewis Capaldi\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (461, '\n\n	\n	\n		\n					Circles		\n	\n', '\n	\n	Post Malone\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (462, '\n\n	\n	\n		\n					Bichota		\n	\n', '\n	\n	Karol G\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (463, '\n\n	\n	\n		\n					Shallow		\n	\n', '\n	\n	Lady Gaga & Bradley Cooper\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (464, '\n\n	\n	\n		\n					Dreams		\n	\n', '\n	\n	Fleetwood Mac\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (465, '\n\n	\n	\n		\n					Sweater Weather		\n	\n', '\n	\n	The Neighbourhood\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (466, '\n\n	\n	\n		\n					Wellerman		\n	\n', '\n	\n	Nathan Evans\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (467, '\n\n	\n	\n		\n					Whats Poppin		\n	\n', '\n	\n	Jack Harlow Featuring DaBaby, Tory Lanez & Lil Wayne\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (468, '\n\n	\n	\n		\n					Need To Know		\n	\n', '\n	\n	Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (469, '\n\n	\n	\n		\n					Lovely		\n	\n', '\n	\n	Billie Eilish & Khalid\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (470, '\n\n	\n	\n		\n					Pepas		\n	\n', '\n	\n	Farruko\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (471, '\n\n	\n	\n		\n					Permission To Dance		\n	\n', '\n	\n	BTS\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (472, '\n\n	\n	\n		\n					Beautiful Mistakes		\n	\n', '\n	\n	Maroon 5 Featuring Megan Thee Stallion\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (473, '\n\n	\n	\n		\n					Bandido		\n	\n', '\n	\n	Myke Towers & Juhn\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (474, '\n\n	\n	\n		\n					Old Town Road		\n	\n', '\n	\n	Lil Nas X Featuring Billy Ray Cyrus\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (475, '\n\n	\n	\n		\n					Calling My Phone		\n	\n', '\n	\n	Lil Tjay Featuring 6LACK\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (476, '\n\n	\n	\n		\n					I Wanna Be Your Slave		\n	\n', '\n	\n	Maneskin\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (477, '\n\n	\n	\n		\n					Wants And Needs		\n	\n', '\n	\n	Drake Featuring Lil Baby\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (478, '\n\n	\n	\n		\n					Good Days		\n	\n', '\n	\n	SZA\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (479, '\n\n	\n	\n		\n					Memories		\n	\n', '\n	\n	Maroon 5\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (480, '\n\n	\n	\n		\n					Senorita		\n	\n', '\n	\n	Shawn Mendes & Camila Cabello\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (481, '\n\n	\n	\n		\n					Telepatia		\n	\n', '\n	\n	Kali Uchis\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (482, '\n\n	\n	\n		\n					Happier Than Ever		\n	\n', '\n	\n	Billie Eilish\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (483, '\n\n	\n	\n		\n					Arcade		\n	\n', '\n	\n	Duncan Laurence\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (484, '\n\n	\n	\n		\n					La Curiosidad		\n	\n', '\n	\n	DJ Nelson Presenta Jay Wheeler & Myke Towers\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (485, '\n\n	\n	\n		\n					Holy		\n	\n', '\n	\n	Justin Bieber Featuring Chance The Rapper\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (486, '\n\n	\n	\n		\n					Best Friend		\n	\n', '\n	\n	Saweetie Featuring Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (487, '\n\n	\n	\n		\n					Bohemian Rhapsody		\n	\n', '\n	\n	Queen\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (488, '\n\n	\n	\n		\n					Closer		\n	\n', '\n	\n	The Chainsmokers Featuring Halsey\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (489, '\n\n	\n	\n		\n					Lonely		\n	\n', '\n	\n	Justin Bieber & benny blanco\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (490, '\n\n	\n	\n		\n					All I Want For Christmas Is You		\n	\n', '\n	\n	Mariah Carey\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (491, '\n\n	\n	\n		\n					All Of Me		\n	\n', '\n	\n	John Legend\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (492, '\n\n	\n	\n		\n					Que Mas Pues?		\n	\n', '\n	\n	J Balvin & Maria Becerra\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (493, '\n\n	\n	\n		\n					Hold On		\n	\n', '\n	\n	Justin Bieber\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (494, '\n\n	\n	\n		\n					Despacito		\n	\n', '\n	\n	Luis Fonsi & Daddy Yankee Featuring Justin Bieber\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (495, '\n\n	\n	\n		\n					Goosebumps		\n	\n', '\n	\n	Travis Scott\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (496, '\n\n	\n	\n		\n					Pareja del Ano		\n	\n', '\n	\n	Sebastian Yatra X Myke Towers\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (497, '\n\n	\n	\n		\n					Anyone		\n	\n', '\n	\n	Justin Bieber\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (498, '\n\n	\n	\n		\n					Prisoner		\n	\n', '\n	\n	Miley Cyrus Featuring Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (499, '\n\n	\n	\n		\n					Woman		\n	\n', '\n	\n	Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (500, '\n\n	\n	\n		\n					Say You Won\'t Let Go		\n	\n', '\n	\n	James Arthur\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (501, '\n\n	\n	\n		\n					Willow		\n	\n', '\n	\n	Taylor Swift\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (502, '\n\n	\n	\n		\n					Love Nwantiti (Ah Ah Ah)		\n	\n', '\n	\n	CKay\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (503, '\n\n	\n	\n		\n					Happier		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (504, '\n\n	\n	\n		\n					Paradise		\n	\n', '\n	\n	MEDUZA & Dermot Kennedy\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (505, '\n\n	\n	\n		\n					My Ex\'s Best Friend		\n	\n', '\n	\n	Machine Gun Kelly X blackbear\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (506, '\n\n	\n	\n		\n					Ride It.		\n	\n', '\n	\n	Regard\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (507, '\n\n	\n	\n		\n					Fancy Like		\n	\n', '\n	\n	Walker Hayes\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (508, '\n\n	\n	\n		\n					Midnight Sky		\n	\n', '\n	\n	Miley Cyrus\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (509, '\n\n	\n	\n		\n					Reloj		\n	\n', '\n	\n	Rauw Alejandro & Anuel AA\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (510, '\n\n	\n	\n		\n					Life Is Good		\n	\n', '\n	\n	Future Featuring Drake\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (511, '\n\n	\n	\n		\n					Don\'t Stop Believin\'		\n	\n', '\n	\n	Journey\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (512, '\n\n	\n	\n		\n					Your Love (9PM)		\n	\n', '\n	\n	ATB x Topic x A7S\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (513, '\n\n	\n	\n		\n					Smells Like Teen Spirit		\n	\n', '\n	\n	Nirvana\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (514, '\n\n	\n	\n		\n					I Don\'t Care		\n	\n', '\n	\n	Ed Sheeran & Justin Bieber\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (515, '\n\n	\n	\n		\n					911		\n	\n', '\n	\n	Sech & Jhay Cortez\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (516, '\n\n	\n	\n		\n					Forever After All		\n	\n', '\n	\n	Luke Combs\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (517, '\n\n	\n	\n		\n					Cold Heart (PNAU Remix)		\n	\n', '\n	\n	Elton John & Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (518, '\n\n	\n	\n		\n					Shivers		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (519, '\n\n	\n	\n		\n					Take Me To Church		\n	\n', '\n	\n	Hozier\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (520, '\n\n	\n	\n		\n					Love Tonight		\n	\n', '\n	\n	Shouse\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (521, '\n\n	\n	\n		\n					Monster		\n	\n', '\n	\n	Shawn Mendes & Justin Bieber\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (522, '\n\n	\n	\n		\n					Dior		\n	\n', '\n	\n	Pop Smoke\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (523, '\n\n	\n	\n		\n					Rain On Me		\n	\n', '\n	\n	Lady Gaga & Ariana Grande\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (524, '\n\n	\n	\n		\n					Thinking Out Loud		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (525, '\n\n	\n	\n		\n					Way 2 Sexy		\n	\n', '\n	\n	Drake Featuring Future & Young Thug\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (526, '\n\n	\n	\n		\n					Hotel California		\n	\n', '\n	\n	Eagles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (527, '\n\n	\n	\n		\n					Easy On Me		\n	\n', '\n	\n	Adele\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (528, '\n\n	\n	\n		\n					Say So		\n	\n', '\n	\n	Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (529, '\n\n	\n	\n		\n					Breaking Me		\n	\n', '\n	\n	Topic & A7S\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (530, '\n\n	\n	\n		\n					Favorite Crime		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (531, '\n\n	\n	\n		\n					Laugh Now Cry Later		\n	\n', '\n	\n	Drake Featuring Lil Durk\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (532, '\n\n	\n	\n		\n					We\'re Good		\n	\n', '\n	\n	Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (533, '\n\n	\n	\n		\n					Life Goes On		\n	\n', '\n	\n	BTS\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (534, '\n\n	\n	\n		\n					Something Just Like This		\n	\n', '\n	\n	The Chainsmokers & Coldplay\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (535, '\n\n	\n	\n		\n					You Right		\n	\n', '\n	\n	Doja Cat & The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (536, '\n\n	\n	\n		\n					Counting Stars		\n	\n', '\n	\n	OneRepublic\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (537, '\n\n	\n	\n		\n					On Me		\n	\n', '\n	\n	Lil Baby\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (538, '\n\n	\n	\n		\n					Leave Before You Love Me		\n	\n', '\n	\n	Marshmello X Jonas Brothers\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (539, '\n\n	\n	\n		\n					Girl Like Me		\n	\n', '\n	\n	Black Eyed Peas X Shakira\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (540, '\n\n	\n	\n		\n					Botella Tras Botella		\n	\n', '\n	\n	Gera MX + Christian Nodal\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (541, '\n\n	\n	\n		\n					Monster		\n	\n', '\n	\n	YOASOBI\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (542, '\n\n	\n	\n		\n					Sweet Child O\' Mine		\n	\n', '\n	\n	Guns N\' Roses\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (543, '\n\n	\n	\n		\n					Last Christmas		\n	\n', '\n	\n	Wham!\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (544, '\n\n	\n	\n		\n					El Makinon		\n	\n', '\n	\n	Karol G & Mariah Angeliq\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (545, '\n\n	\n	\n		\n					Adore You		\n	\n', '\n	\n	Harry Styles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (546, '\n\n	\n	\n		\n					Take My Breath		\n	\n', '\n	\n	The Weeknd\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (547, '\n\n	\n	\n		\n					Relacion		\n	\n', '\n	\n	Sech, Daddy Yankee & J Balvin Featuring Rosalia & Farruko\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (548, '\n\n	\n	\n		\n					Go Crazy		\n	\n', '\n	\n	Chris Brown & Young Thug\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (549, '\n\n	\n	\n		\n					Back In Blood		\n	\n', '\n	\n	Pooh Shiesty Featuring Lil Durk\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (550, '\n\n	\n	\n		\n					Kings & Queens		\n	\n', '\n	\n	Ava Max\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (551, '\n\n	\n	\n		\n					Intentions		\n	\n', '\n	\n	Justin Bieber Featuring Quavo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (552, '\n\n	\n	\n		\n					Afterglow		\n	\n', '\n	\n	Ed Sheeran\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (553, '\n\n	\n	\n		\n					Volvi		\n	\n', '\n	\n	Aventura x Bad Bunny\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (554, '\n\n	\n	\n		\n					My Universe		\n	\n', '\n	\n	Coldplay x BTS\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (555, '\n\n	\n	\n		\n					Brutal		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (556, '\n\n	\n	\n		\n					Talking To The Moon		\n	\n', '\n	\n	Bruno Mars\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (557, '\n\n	\n	\n		\n					Jealousy, Jealousy		\n	\n', '\n	\n	Olivia Rodrigo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (558, '\n\n	\n	\n		\n					Ain\'t Shit		\n	\n', '\n	\n	Doja Cat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (559, '\n\n	\n	\n		\n					My Head And My Heart		\n	\n', '\n	\n	Ava Max\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (560, '\n\n	\n	\n		\n					Mienteme		\n	\n', '\n	\n	TINI X Maria Becerra\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (561, '\n\n	\n	\n		\n					Bed		\n	\n', '\n	\n	Joel Corry X RAYE X David Guetta\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (562, '\n\n	\n	\n		\n					The Box		\n	\n', '\n	\n	Roddy Ricch\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (563, '\n\n	\n	\n		\n					Cover Me In Sunshine		\n	\n', '\n	\n	P!nk + Willow Sage Hart\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (564, '\n\n	\n	\n		\n					Body		\n	\n', '\n	\n	Megan Thee Stallion\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (565, '\n\n	\n	\n		\n					Beat Box		\n	\n', '\n	\n	SpotemGottem Featuring Pooh Shiesty Or DaBaby\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (566, '\n\n	\n	\n		\n					Sicko Mode		\n	\n', '\n	\n	Travis Scott\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (567, '\n\n	\n	\n		\n					Fair Trade		\n	\n', '\n	\n	Drake Featuring Travis Scott\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (568, '\n\n	\n	\n		\n					Knife Talk		\n	\n', '\n	\n	Drake Featuring 21 Savage & Project Pat\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (569, '\n\n	\n	\n		\n					Rockin\' Around The Christmas Tree		\n	\n', '\n	\n	Brenda Lee\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (570, '\n\n	\n	\n		\n					Girls Want Girls		\n	\n', '\n	\n	Drake Featuring Lil Baby\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (571, '\n\n	\n	\n		\n					Yellow		\n	\n', '\n	\n	Coldplay\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (572, '\n\n	\n	\n		\n					Take You Dancing		\n	\n', '\n	\n	Jason Derulo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (573, '\n\n	\n	\n		\n					Body		\n	\n', '\n	\n	Tion Wayne X Russ Millions Featuring ArrDee, E1 (3x3), ZT (3x3), Bugzy Malone, Buni, Fivio Foreign & Darkoo\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (574, '\n\n	\n	\n		\n					Build A Bitch		\n	\n', '\n	\n	Bella Poarch\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (575, '\n\n	\n	\n		\n					Lucid Dreams		\n	\n', '\n	\n	Juice WRLD\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (576, '\n\n	\n	\n		\n					Death Bed		\n	\n', '\n	\n	Powfu Featuring beabadoobee\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (577, '\n\n	\n	\n		\n					Hecha Pa\' Mi		\n	\n', '\n	\n	Boza\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (578, '\n\n	\n	\n		\n					Baila Conmigo		\n	\n', '\n	\n	Selena Gomez With Rauw Alejandro\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (579, '\n\n	\n	\n		\n					What\'s Next		\n	\n', '\n	\n	Drake\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (580, '\n\n	\n	\n		\n					Another Love		\n	\n', '\n	\n	Tom Odell\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (581, '\n\n	\n	\n		\n					Break My Heart		\n	\n', '\n	\n	Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (582, '\n\n	\n	\n		\n					Jingle Bell Rock		\n	\n', '\n	\n	Bobby Helms\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (583, '\n\n	\n	\n		\n					Dry Flower		\n	\n', '\n	\n	Yuuri\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (584, '\n\n	\n	\n		\n					Jerusalema		\n	\n', '\n	\n	Master KG Featuring Burna Boy & Nomcebo Zikode\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (585, '\n\n	\n	\n		\n					How You Like That		\n	\n', '\n	\n	BLACKPINK\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (586, '\n\n	\n	\n		\n					Highest In The Room		\n	\n', '\n	\n	Travis Scott\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (587, '\n\n	\n	\n		\n					Mood Swings		\n	\n', '\n	\n	Pop Smoke Featuring Lil Tjay\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (588, '\n\n	\n	\n		\n					Love Again		\n	\n', '\n	\n	Dua Lipa\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (589, '\n\n	\n	\n		\n					Holiday		\n	\n', '\n	\n	Lil Nas X\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (590, '\n\n	\n	\n		\n					Golden		\n	\n', '\n	\n	Harry Styles\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (591, '\n\n	\n	\n		\n					Volando		\n	\n', '\n	\n	Mora, Bad Bunny & Sech\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (592, '\n\n	\n	\n		\n					Run		\n	\n', '\n	\n	OneRepublic\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (593, '\n\n	\n	\n		\n					2/Catorce		\n	\n', '\n	\n	Rauw Alejandro X Mr. Naisgai\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (594, '\n\n	\n	\n		\n					Thunderstruck		\n	\n', '\n	\n	AC/DC\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (595, '\n\n	\n	\n		\n					Essence		\n	\n', '\n	\n	Wizkid Featuring Justin Bieber & Tems\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (596, '\n\n	\n	\n		\n					Follow You		\n	\n', '\n	\n	Imagine Dragons\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (597, '\n\n	\n	\n		\n					Starboy		\n	\n', '\n	\n	The Weeknd Featuring Daft Punk\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (598, '\n\n	\n	\n		\n					In Da Getto		\n	\n', '\n	\n	J Balvin & Skrillex\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (599, '\n\n	\n	\n		\n					La Toxica		\n	\n', '\n	\n	Farruko\n');
INSERT INTO `global200` (`rank`, `title`, `singer`) VALUES (600, '\n\n	\n	\n		\n					La Nota		\n	\n', '\n	\n	Manuel Turizo, Myke Towers & Rauw Alejandro\n');
